### PR TITLE
1.6.0 Interface Upgrades

### PR DESCRIPTION
**Pull request by SeraEris**
Initial Commit

6 block models added, used existing textures.
Extended tile interface class to ultimater interface class for nested updates ( multiple items per tick ).
Includes legacy registry implementation to provide backwards compatibility with existing mod packs and worlds. Automation Interface will be converted to Basic Interface, the lowest tier.

Rates:
Basic: 1 item per 4 seconds, power draw / 32 ticks
Advanced: 1 item per 2 seconds, power draw / 16 ticks
Elite: 1 item per second, power draw / 8 ticks
Ultimate: 1 item per tick, power draw per tick
Crystaltine: 4 items per tick, power draw x 4 per tick
The Ultimate: 16 items per tick, power draw x16 per tick

### CODE REVIEW

**Comment by Tehelee** [comment]
Backwards compatibility working in latest ozone 3:
Quest Log

**Comment by Tehelee** [comment]
It would also be ideal to view the recipe listing for the attached table without a set recipe.
i.e. enable the recipies button if a valid crafter is beneath; this recipe menu should clone JEI's add button as a save button to store that recipe to the interface without having to place the ingredients in the table.

It's late, and I'll look into it tomorrow unless you have a suggestion on where to tackle this.

**Comment by Tehelee** [comment]
Additionally lower tier interfaces should not work with higher tier tables ( basic interface wont work on an advance table ), however higher tiers should work on their tier and lower.

**Comment by BlakeBr0** [comment]
As I don't plan to maintain the 1.12 version anymore, and the Automation Interface will be removed, I won't be pulling this. I think the replacement I have planned should accomplish a lot of what this was going for.

**Pull request closed without merging**
